spring.application.name=board-game-buddy
# instead of using this property which is not the best idea,we should set the API key to an environnement variable named SPRING_AI_OPENAI_API_KEY
spring.ai.openai.api-key=
